"""Metric-readout CONTROLS (q19 §Validation): synthetic models with KNOWN behaviour.

These validate that the M1/M2/M3 READOUTS report the right thing, independently of whether the REAL model
steers. A tiny fake model steers (or not) in a known way; the readout must recover it. This is the guard
that catches a metric bug (offset-arithmetic tautology, leakage, indexing) before the GPU run.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import torch
from scipy.stats import nbinom

from sandbox import SANDBOX_ASSAYS
from sandbox.diagnostics.dual_conditioning_real import metrics_real
from sandbox.diagnostics.dual_conditioning_real.metrics_real import (
    H5_ASSAY_ORDER,
    EvalUnit, _bootstrap_ci, _cluster_bootstrap_ci, _flip_covariate, _depth_sweep, _flip_read_length,
    _foreground_mask, _leave_group_out_nearest_centroid, _marginal_nb, _metadata_ablation,
    _oracle_scale, _recoverability_probe, eval_M1, eval_M3,
    DEPTH_ROW, RUN_TYPE_ROW, READLEN_ROW,
)
from sandbox.diagnostics.dual_conditioning.metrics import nb_crps
from sandbox.diagnostics.dual_conditioning_real.tests.fixture import bake_fixture

CPU = torch.device("cpu")


# ---------------------------------------------------------------------------
# fake decoder models with a KNOWN steering law
# ---------------------------------------------------------------------------

class FakeM2Model:
    """decoder(z, y_meta) -> {mu,n,p,eta,log2_mu} following a chosen law; encode() -> dummy z."""

    def __init__(self, kind, center=25.0, n_const=5.0, slope=1.0, rt_gain=3.0, const_log2mu=3.0,
                 clamp_lo=-float("inf"), clamp_hi=float("inf")):
        self.kind, self.center, self.n_const = kind, center, n_const
        self.slope, self.rt_gain, self.const_log2mu = slope, rt_gain, const_log2mu
        self.clamp_lo, self.clamp_hi = clamp_lo, clamp_hi        # mirrors the real decoder's log2_mu clamp

    def encode(self, x_data, x_dna, x_meta):
        B, L, _ = x_data.shape
        return torch.zeros(B, L, 2)

    def decoder(self, z, y_meta):
        B, L, _ = z.shape
        A = y_meta.shape[2]
        depth = y_meta[:, DEPTH_ROW, :]
        rt = y_meta[:, RUN_TYPE_ROW, :]
        if self.kind == "offset_only":                       # mu=2^(d-center), eta=0 (pure arithmetic)
            log2mu = depth - self.center
            eta = torch.zeros_like(depth)
        elif self.kind == "eta_depth":                       # eta tracks depth (learned), offset off
            eta = self.slope * (depth - self.center)
            log2mu = eta
        elif self.kind == "offset_plus_eta":                 # HYBRID: offset AND a learned eta response
            eta = self.slope * (depth - self.center)
            log2mu = (depth - self.center) + eta             # total slope = 1 + slope
        elif self.kind == "depth_ignore":                    # constant, depth ignored
            eta = torch.full_like(depth, self.const_log2mu)
            log2mu = eta
        elif self.kind == "rt_responsive":                   # mu depends on run_type
            gain = torch.where(rt == 1.0, torch.full_like(rt, self.rt_gain), torch.ones_like(rt))
            log2mu = (depth - self.center) + torch.log2(gain)
            eta = torch.zeros_like(depth)
        elif self.kind == "rt_ignore":                       # run_type ignored
            log2mu = depth - self.center
            eta = torch.zeros_like(depth)
        elif self.kind == "assay_presence_only":
            # Responds ONLY to "is this slot present?" (assay_id == MISSING sentinel), and is bit-exactly
            # blind to WHICH assay it is. A whole-row assay_id permutation moves the sentinel across
            # slots and reads this as large "assay steering"; the honest probe must read zero.
            aid = y_meta[:, 1, :]
            eta = torch.where(aid < 0, torch.full_like(aid, self.rt_gain), torch.zeros_like(aid))
            log2mu = (depth - self.center) + eta
        else:
            raise ValueError(self.kind)
        log2mu = log2mu.clamp(self.clamp_lo, self.clamp_hi)
        mu = torch.pow(2.0, log2mu).clamp_min(1e-6)
        n = torch.full_like(mu, self.n_const)
        p = (n / (n + mu)).clamp(1e-9, 1.0 - 1e-9)
        exp = lambda t: t.unsqueeze(1).expand(B, L, A)
        return dict(mu=exp(mu), n=exp(n), p=exp(p), eta=exp(eta), log2_mu=exp(log2mu))


def _m2_unit(model, *, true_depth=25.0, true_rt=1.0, a=0, B=4, L=64, seed=0) -> EvalUnit:
    """Synthetic held-out-target unit whose GT is generated by `model` at the TRUE prompt."""
    ym = torch.full((B, 4, 8), -1.0)
    ym[:, DEPTH_ROW, a] = true_depth
    ym[:, 1, a] = float(a)
    ym[:, READLEN_ROW, a] = 76.0
    ym[:, RUN_TYPE_ROW, a] = true_rt
    out = model.decoder(torch.zeros(B, L, 2), ym)
    mu = out["mu"][:, :, a].numpy()
    n = out["n"][:, :, a].numpy()
    p = np.clip(n / (n + mu), 1e-9, 1.0 - 1e-9)
    gt = nbinom.rvs(n, p, random_state=np.random.default_rng(seed)).astype(np.float64)
    y_data_imp = torch.full((B, L, 8), -1.0)
    y_data_imp[:, :, a] = torch.tensor(gt, dtype=torch.float32)
    imp_map = torch.zeros(B, L, 8, dtype=torch.bool)
    imp_map[:, :, a] = True
    return EvalUnit(z=torch.zeros(B, L, 2), y_meta_true=ym.clone(),
                    den_map=torch.zeros(B, L, 8, dtype=torch.bool), y_data=torch.zeros(B, L, 8),
                    imp_map=imp_map, y_data_imp=y_data_imp, y_meta_imp=ym.clone(),
                    y_avail=torch.zeros(B, 8), biosample="T_x", imp_biosample="B_x")


# ---------------------------------------------------------------------------
# M2 depth controls
# ---------------------------------------------------------------------------

def test_depth_offset_only_flags_arithmetic_not_learned():
    m = FakeM2Model("offset_only")
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
    t = res["per_target"][0]
    assert t["min_at_true"]                                   # CRPS-curve min at the true depth
    assert (max(t["crps_curve"]) - min(t["crps_curve"])) > 1e-3   # curve varies (offset arithmetic works)
    assert abs(res["median_eta_slope"]) < 1e-3               # BUT eta-slope ~ 0 -> "arithmetic, not learned"
    assert not res["offset_independent"]


def test_depth_eta_learned_positive_control():
    m = FakeM2Model("eta_depth", slope=1.0)
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=1)
    assert res["median_eta_slope"] > 0.5                    # eta tracks told depth ~ slope
    assert res["offset_independent"]


def test_depth_ignoring_negative_control():
    m = FakeM2Model("depth_ignore")
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=2)
    t = res["per_target"][0]
    assert (max(t["crps_curve"]) - min(t["crps_curve"])) < 1e-6    # flat curve -> no steering
    assert abs(res["median_eta_slope"]) < 1e-6


def test_depth_shuffle_null_collapses():
    # on a responsive (offset-only) model, the shuffled-prompt null should not beat the true prompt.
    m = FakeM2Model("offset_only")
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0, B=8)], CPU, fg_frac=0.5, n_boot=50, seed=3)
    t = res["per_target"][0]
    assert t["dir_mean_delta"] > 0                           # true beats most-downsampled (direction)
    # null (shuffled depth across samples) delta ~ 0 relative to the direction effect
    assert abs(t["null_mean_delta"]) < 0.5 * abs(t["dir_mean_delta"]) + 1e-6


# ---------------------------------------------------------------------------
# S1 (h48) — TOTAL told-depth slope + cross-target metadata ablation
#
# `eta_slope` scores the offset-FREE residual, so it measures WHERE the depth response is implemented,
# not WHETHER the model responds (audit S1). The primary instrument is the TOTAL slope
# d<log2_mu>/d(told depth), which must read 1.0 for a correct exposure model however it is built.
# ---------------------------------------------------------------------------

def _bruteforce_total_slope(model, u, a, fg_frac):
    """Independent recomputation of the total told-depth slope: hand-built mask + gather, and a
    least-squares fit via `np.linalg.lstsq` (the instrument uses `np.polyfit`)."""
    m = u.imp_map[:, :, a]
    tgt = u.y_data_imp[:, :, a][m].double().cpu().numpy()
    fg = tgt >= np.quantile(tgt, 1.0 - fg_frac)
    if fg.sum() < 5:
        fg = np.ones_like(fg, bool)
    base_d = u.y_meta_imp[:, DEPTH_ROW, a]
    xs, ys = [], []
    for k in (1, 2, 4, 8):
        dvec = base_d - float(np.log2(k))
        ym = u.y_meta_true.clone()
        ym[:, DEPTH_ROW, a] = dvec
        lm = model.decoder(u.z, ym)["log2_mu"][:, :, a][m].double().cpu().numpy()
        xs.append(float(dvec.float().mean()))
        ys.append(float(lm[fg].mean()))
    design = np.vstack([np.array(xs), np.ones(len(xs))]).T
    return float(np.linalg.lstsq(design, np.array(ys), rcond=None)[0][0])


def test_s1_L_total_slope_offset_only_is_exactly_one():
    # eta == 0 by construction => the whole depth response is the offset => total slope EXACTLY 1.
    m = FakeM2Model("offset_only")
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
    assert abs(res["median_total_slope"] - 1.0) < 1e-9
    assert res["total_slope_err"] < 1e-9
    assert abs(res["median_eta_slope"]) < 1e-9         # the demoted diagnostic correctly reads "no eta"


def test_s1_L_total_slope_eta_only_recovers_k():
    # offset OFF, eta = k*(d-c) => total slope must be k (NOT 1, and NOT 0).
    for k in (0.6, 1.0):
        m = FakeM2Model("eta_depth", slope=k)
        res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
        assert abs(res["median_total_slope"] - k) < 1e-6
        assert abs(res["median_eta_slope"] - k) < 1e-6      # offset off => total == eta


def test_s1_L_total_slope_hybrid_recovers_one_plus_k():
    # the hybrid the old bar forbade: total = beta + eta_slope with beta = 1.
    k = 0.6
    m = FakeM2Model("offset_plus_eta", slope=k)
    res = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
    assert abs(res["median_total_slope"] - (1.0 + k)) < 1e-6
    assert abs(res["median_eta_slope"] - k) < 1e-6
    # ...and it is the total, not eta_slope, that exposes the over-response.
    assert res["total_slope_err"] > 0.5


def test_s1_C_total_slope_matches_bruteforce_and_finite_difference():
    for kind, kw in (("offset_only", {}), ("eta_depth", dict(slope=0.6)),
                     ("offset_plus_eta", dict(slope=0.6))):
        m = FakeM2Model(kind, **kw)
        u = _m2_unit(m, true_depth=25.0)
        res = _depth_sweep(m, [u], CPU, fg_frac=0.5, n_boot=50, seed=0)
        t = res["per_target"][0]
        assert abs(t["total_slope"] - _bruteforce_total_slope(m, u, 0, 0.5)) < 1e-6
        # these stubs are exactly linear in told depth, so the endpoint finite difference must agree
        fd = ((t["log2mu_means"][-1] - t["log2mu_means"][0])
              / (t["told_depth"][-1] - t["told_depth"][0]))
        assert abs(t["total_slope"] - fd) < 1e-6


def test_s1_C_total_slope_flags_clamp_saturation():
    """A slope read through a saturating `log2_mu` clamp is not an exposure coefficient. A model with a
    true slope of 1 whose output is floored must be FLAGGED, not reported as a sub-unit response."""
    m = FakeM2Model("offset_only", center=25.0)
    clean = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
    assert clean["median_frac_log2mu_at_clamp"] == 0.0 and not clean["total_slope_clamp_saturated"]

    m.clamp_lo, m.clamp_hi = -1.0, 30.0            # floor most of the sweep (told depths run 22..25)
    sat = _depth_sweep(m, [_m2_unit(m, true_depth=25.0)], CPU, fg_frac=0.5, n_boot=50, seed=0)
    assert sat["median_frac_log2mu_at_clamp"] > 0.5
    assert sat["total_slope_clamp_saturated"]      # the guard fires...
    assert sat["median_total_slope"] < 0.9         # ...on a slope that would otherwise read as sub-unit


def test_s1_L_ablation_separates_responsive_from_blind():
    m = FakeM2Model("rt_responsive", rt_gain=3.0)
    units = [_m2_unit(m, true_rt=1.0, a=0, seed=0), _m2_unit(m, true_rt=0.0, a=1, seed=1)]
    res = _metadata_ablation(m, units, RUN_TYPE_ROW, fg_frac=0.5, seed=0)
    assert res["n_targets"] == 2
    assert res["mean_d_crps"] > 0                      # honest prompt beats the cross-target swap
    assert res["mean_abs_d_mu"] > 0
    assert res["frac_true_better"] == 1.0

    mb = FakeM2Model("rt_ignore")
    ub = [_m2_unit(mb, true_rt=1.0, a=0, seed=0), _m2_unit(mb, true_rt=0.0, a=1, seed=1)]
    resb = _metadata_ablation(mb, ub, RUN_TYPE_ROW, fg_frac=0.5, seed=0)
    assert resb["n_targets"] == 2
    assert resb["mean_d_crps"] == 0.0                  # blind to the row => bit-exactly no effect
    assert resb["mean_abs_d_mu"] == 0.0 and resb["mean_abs_d_eta"] == 0.0
    assert not resb["uses_covariate"]


def test_s1_L_ablation_is_not_fooled_by_a_presence_detector():
    """LOAD-BEARING sentinel control (the h47 V2 anchor protocol fails this one).

    A decoder that reacts only to the MISSING sentinel -- "is this slot present?" -- and is bit-exactly
    blind to assay IDENTITY must read ZERO on an assay-identity probe. A whole-row `assay_id`
    permutation does not: it slides the sentinel across slots and reports a large response.
    """
    m = FakeM2Model("assay_presence_only", rt_gain=3.0)
    units = [_m2_unit(m, a=0, seed=0), _m2_unit(m, a=1, seed=1)]

    honest = _metadata_ablation(m, units, 1, fg_frac=0.5, seed=0)      # row 1 = assay_id, real -> real
    assert honest["n_targets"] == 2
    assert honest["max_abs_d_eta"] == 0.0 and honest["mean_d_crps"] == 0.0
    assert not honest["uses_covariate"]                                # correct verdict: identity-blind

    # the contaminated protocol: permute the WHOLE assay_id row, measure max|d eta| over every slot.
    u = units[0]
    ym = u.y_meta_true.clone()
    ym[:, 1, :] = torch.roll(u.y_meta_true[:, 1, :], shifts=1, dims=1)
    fooled = (m.decoder(u.z, ym)["eta"] - m.decoder(u.z, u.y_meta_true)["eta"]).abs().max().item()
    assert fooled > 1.0                                                # ...reads "steering" on a blind model


def test_s1_C_ablation_is_cross_target_and_within_batch_is_the_B3_identity():
    m = FakeM2Model("rt_responsive", rt_gain=3.0)
    units = [_m2_unit(m, true_rt=1.0, a=0, seed=0), _m2_unit(m, true_rt=0.0, a=1, seed=1)]
    res = _metadata_ablation(m, units, RUN_TYPE_ROW, fg_frac=0.5, seed=0)
    for t in res["per_target"]:
        assert t["swapped_value"] != t["true_value"]   # the swap really changed the prompt
    # B3: one natural value per (biosample, assay) => a WITHIN-BATCH permutation is the identity, so the
    # degenerate control must report "no effect" even on a model that provably responds.
    wb = _metadata_ablation(m, units, RUN_TYPE_ROW, mode="within_batch", fg_frac=0.5, seed=0)
    assert wb["mean_abs_d_mu"] == 0.0 and wb["mean_d_crps"] == 0.0
    assert res["mean_abs_d_mu"] > 0.0


# ---------------------------------------------------------------------------
# S3 (h48) — rank-based foreground selection
#
# `target >= quantile(target, 1-fg_frac)` degenerates on sparse tracks: when the 98th percentile is 0,
# `target >= 0` selects everything. Requested 2%, realised 23.9%, 21.6% of records at 100% (audit S3).
# ---------------------------------------------------------------------------

def test_s3_L_selects_exactly_the_top_k_at_the_requested_fraction():
    rng = np.random.default_rng(0)
    target = rng.integers(1, 50, size=1000).astype(np.float64)   # dense: purity filter is a no-op
    for frac in (0.02, 0.05, 0.10):
        fg = _foreground_mask(target, frac)
        k = round(frac * 1000)
        assert fg.sum() == k                                     # realised == requested, exactly
        assert abs(fg.mean() - frac) < 1e-9
        assert set(np.flatnonzero(fg)) == set(np.argsort(target, kind="stable")[-k:])
        assert target[fg].min() >= target[~fg].max()             # genuinely the highest positions


def test_s3_L_sparse_target_does_not_degenerate_to_everything():
    """The two ways the old `target >= quantile(target, 1-frac)` selector blows up on real tracks."""
    # (a) >=98% exact zeros => quantile == 0 => `target >= 0` selects EVERY position (the 21.6%-at-100%).
    a = np.zeros(1000)
    a[:15] = np.arange(1, 16)
    assert (a >= np.quantile(a, 0.98)).mean() == 1.0                     # old: 100%
    fg = _foreground_mask(a, 0.02)
    assert fg.sum() == 15 and 0 < fg.mean() < 1.0                        # new: the 15 real peaks only
    assert set(np.flatnonzero(fg)) == set(range(15))

    # (b) heavy integer ties: counts are small integers, so the 98th percentile lands ON a tied value
    # and `>=` sweeps in the whole tie group.
    b = np.concatenate([np.zeros(600), np.ones(300), np.full(100, 9.0)])
    assert (b >= np.quantile(b, 0.98)).mean() == 0.10                    # old: 5x over-selects
    fgb = _foreground_mask(b, 0.02)
    assert fgb.sum() == 20 and fgb.mean() == 0.02                        # new: exactly 2%
    assert set(np.flatnonzero(fgb)) <= set(range(900, 1000))


def test_s3_L_degenerate_targets_are_never_empty_and_never_everything():
    for target in (np.zeros(500),                                # all-zero
                   np.concatenate([np.zeros(498), [3.0, 9.0]])): # only 2 non-zero, fewer than min_n
        fg = _foreground_mask(target, 0.02)
        assert 0 < fg.sum() < target.size
    only_two = np.concatenate([np.zeros(498), [3.0, 9.0]])
    assert set(np.flatnonzero(_foreground_mask(only_two, 0.02))) >= {498, 499}
    assert _foreground_mask(np.zeros(0), 0.02).size == 0


def test_s3_C_matches_bruteforce_and_is_deterministic():
    rng = np.random.default_rng(3)
    for _ in range(20):
        n = int(rng.integers(50, 3000))
        target = np.where(rng.random(n) < 0.6, 0.0, rng.integers(1, 200, size=n)).astype(np.float64)
        fg = _foreground_mask(target, 0.02)
        assert np.array_equal(fg, _foreground_mask(target, 0.02))          # deterministic
        # brute force: sort descending, walk down taking the k largest, then drop sub-1 counts
        k = min(n, max(5, round(0.02 * n)))
        want = np.zeros(n, bool)
        want[np.array(sorted(range(n), key=lambda i: (target[i], i))[-k:])] = True
        pos = target >= 1.0
        if int(pos.sum()) >= min(5, n):
            want &= pos
        assert np.array_equal(fg, want)
        assert fg.any() and not fg.all()
        if fg.sum():
            assert target[fg].min() >= target[~fg].max()                   # no background above signal


def test_s3_C_realized_fraction_is_reported_per_record():
    m = FakeM2Model("rt_responsive", rt_gain=3.0)
    units = [_m2_unit(m, true_rt=1.0, a=0, seed=0), _m2_unit(m, true_rt=0.0, a=1, seed=1)]
    res = _flip_covariate(m, units, CPU, "run_type", fg_frac=0.1, n_boot=50, seed=0)
    for r in res["per_target"]:
        assert "fg_frac_realized" in r and r["fg_frac_realized"] < 1.0
        assert r["n_fg"] == round(r["fg_frac_realized"] * 4 * 64)
    sw = _depth_sweep(m, units, CPU, fg_frac=0.1, n_boot=50, seed=0)
    assert all(t["fg_frac_realized"] < 1.0 for t in sw["per_target"])
    ab = _metadata_ablation(m, units, RUN_TYPE_ROW, fg_frac=0.1, seed=0)
    assert all(t["fg_frac_realized"] < 1.0 for t in ab["per_target"])


# ---------------------------------------------------------------------------
# S4 (h48) — target-clustered CIs
#
# Effective replication is 12 (biosample, imp_biosample, assay) targets / 5 biosample pairs (bound B4),
# not the ~893k positions the position-level bootstrap resamples => every M2 CI was ~24x too narrow.
# ---------------------------------------------------------------------------

def _recs(cluster_means, n_fg=1000, per_cluster=5, sd=0.001, seed=0):
    """`per_target`-shaped records: `per_cluster` records per target, jittered around its cluster mean.
    Target names are zero-padded so the instrument's `sorted(keys)` order == construction order."""
    rng = np.random.default_rng(seed)
    out = []
    for i, mu in enumerate(cluster_means):
        for _ in range(per_cluster):
            out.append(dict(target=("T_bio%02d" % i, "V_bio%02d" % i, "assay%02d" % i),
                            mean_delta=float(mu + rng.normal(0, sd)), n_fg=n_fg))
    return out


def test_s4_L_one_outlier_target_no_longer_manufactures_significance():
    """11 targets scattered around 0 and 1 large: the position-level CI excludes 0, the clustered one
    must not -- and the target-level sign test must refuse to support it too."""
    means = [0.05, -0.05] * 5 + [-0.05] + [1.2]                # 11 balanced nulls + 1 big outlier
    recs = _recs(means, sd=1e-4, seed=1)
    pos_delta = np.concatenate([np.full(r["n_fg"], r["mean_delta"]) for r in recs])
    old = _bootstrap_ci(pos_delta, n_boot=2000, seed=0)
    new = _cluster_bootstrap_ci(recs, n_boot=2000, seed=0)
    assert old["lo"] > 0 and old["excludes_zero"]              # old: "significant"
    assert new["lo"] < 0 < new["hi"] and not new["excludes_zero"]      # new: not significant
    assert not new["supports_direction"]
    assert new["n_clusters"] == 12 and new["n_records"] == 60
    assert new["sign_test_p"] > 0.05                           # sign test agrees: one target drives it


def test_s4_L_pure_null_clustered_ci_covers_zero_near_95pct():
    covered = 0
    trials = 200
    for s in range(trials):
        means = np.random.default_rng(1000 + s).normal(0, 0.3, size=12)
        ci = _cluster_bootstrap_ci(_recs(means, sd=1e-6, seed=s), n_boot=400, seed=s)
        covered += int(ci["lo"] <= 0.0 <= ci["hi"])
    assert 0.86 <= covered / trials <= 1.0                     # ~95% nominal (bootstrap under-covers a bit)


def test_s4_L_real_effect_still_detected():
    # all 12 targets shifted: the clustered CI must still exclude 0 (the fix costs power, not validity).
    ci = _cluster_bootstrap_ci(_recs([0.5] * 12, sd=0.05, seed=7), n_boot=2000, seed=0)
    assert ci["lo"] > 0 and ci["supports_direction"] and ci["sign"] == 1
    assert ci["n_pos"] == 12 and ci["sign_test_p"] < 0.001


def test_s4_C_resamples_targets_not_positions_and_is_nfg_weighted():
    means = [0.0] * 11 + [1.2]
    recs = _recs(means, sd=0.0, seed=2)
    ci = _cluster_bootstrap_ci(recs, n_boot=1500, seed=0)
    assert ci["n_clusters"] == 12                              # == distinct (bio, imp_bio, assay) keys
    assert len({tuple(r["target"]) for r in recs}) == ci["n_clusters"]
    # records collapse to exactly one value per target, in target order
    assert (np.asarray(ci["cluster_values"]) == np.asarray(means)).all()
    assert ci["mean"] == pytest.approx(float(np.mean(means)), abs=1e-9)   # equal n_fg -> plain mean
    # it resamples TARGETS: with 11 of 12 clusters at exactly 0, the bootstrap mean must land on the
    # 12-cluster multiset lattice (k*1.2/12) -- a 12000-position bootstrap could never do that.
    boot_reachable = {round(k * 1.2 / 12, 12) for k in range(13)}
    assert round(ci["lo"], 12) in boot_reachable and round(ci["hi"], 12) in boot_reachable
    # n_fg weighting: give the outlier 10x the foreground and the weighted mean must move toward it
    heavy = [dict(r, n_fg=(10000 if r["target"][2] == "assay11" else 1000)) for r in recs]
    assert _cluster_bootstrap_ci(heavy, n_boot=200, seed=0)["mean"] > ci["mean"]


def test_s4_C_supports_direction_is_sign_aware():
    """S16: `excludes_zero` is sign-blind -- a significant effect in the WRONG direction satisfies it."""
    wrong = _cluster_bootstrap_ci(_recs([-0.5] * 12, sd=0.05, seed=9), n_boot=2000, seed=0)
    assert wrong["excludes_zero"]                              # ...as the old flag would report
    assert not wrong["supports_direction"] and wrong["sign"] == -1     # ...but the direction is wrong


def test_s4_C_clustered_ci_is_wired_into_the_M2_readouts():
    m = FakeM2Model("rt_responsive", rt_gain=3.0)
    units = [_m2_unit(m, true_rt=1.0, a=0, seed=0), _m2_unit(m, true_rt=0.0, a=1, seed=1)]
    fl = _flip_covariate(m, units, CPU, "run_type", fg_frac=0.5, n_boot=200, seed=0)
    assert fl["overall_clustered"]["n_clusters"] == 2 and "supports_direction" in fl["overall_clustered"]
    sw = _depth_sweep(m, units, CPU, fg_frac=0.5, n_boot=200, seed=0)
    assert sw["direction_clustered"]["n_clusters"] == 2 and sw["null_clustered"]["n_clusters"] == 2
    ab = _metadata_ablation(m, units, RUN_TYPE_ROW, fg_frac=0.5, seed=0)
    assert ab["d_crps_clustered"]["n_clusters"] == 2


# ---------------------------------------------------------------------------
# M2 run_type controls
# ---------------------------------------------------------------------------

def test_runtype_responsive_direction_and_responsiveness():
    m = FakeM2Model("rt_responsive", rt_gain=3.0)
    res = _flip_covariate(m, [_m2_unit(m, true_rt=1.0)], CPU, "run_type", fg_frac=0.5, n_boot=100, seed=0)
    t = res["per_target"][0]
    assert t["responsiveness"] > 0                           # flipping changes the predicted NB
    assert t["direction_true_better"]                        # CRPS(true,GT) < CRPS(flip,GT)
    assert res["overall"]["mean"] > 0
    assert res["frac_direction"] == 1.0


def test_runtype_ignoring_honest_null():
    m = FakeM2Model("rt_ignore")
    res = _flip_covariate(m, [_m2_unit(m, true_rt=1.0)], CPU, "run_type", fg_frac=0.5, n_boot=100, seed=0)
    t = res["per_target"][0]
    assert t["responsiveness"] < 1e-6                        # flip does not move the prediction
    assert res["natural_variance_insufficient"]              # honest-null path, NOT "refuted"


def test_flip_read_length_goes_to_farthest_observed():
    ym = torch.full((2, 4, 8), -1.0)
    ym[:, READLEN_ROW, 0] = 76.0
    out = _flip_read_length(ym, 0)
    assert torch.all(out[:, READLEN_ROW, 0] == 30.0)         # farthest of {30,36,76,100,101} from 76
    ym[:, READLEN_ROW, 0] = 30.0
    out2 = _flip_read_length(ym, 0)
    assert torch.all(out2[:, READLEN_ROW, 0] == 101.0)


# ---------------------------------------------------------------------------
# S5/S18 (h48) — honest per-assay marginal + oracle scale decomposition
# ---------------------------------------------------------------------------

def _nb_sample(mu, n, size, seed):
    p = n / (n + mu)
    return nbinom.rvs(n, p, size=size, random_state=np.random.default_rng(seed)).astype(np.float64)


def test_s5_L_oracle_recovers_an_injected_scale():
    """mu = truth * 2^c0 => c* must recover -c0 and the residual must fall to the shape floor."""
    n_true, mu_true = 4.0, 12.0
    y = _nb_sample(mu_true, n_true, 20000, 0)
    n = np.full_like(y, n_true)
    for c0 in (-2.0, -0.75, 0.0, 1.5):
        mu = np.full_like(y, mu_true * 2.0 ** c0)
        r = _oracle_scale(mu, n, y, seed=0)
        assert abs(r["c_star"] + c0) < 0.06                          # recovers -c0
        crps = float(np.mean(nb_crps(n, np.clip(n / (n + mu), 1e-9, 1 - 1e-9), y)))
        floor = float(np.mean(nb_crps(n, np.clip(n / (n + mu_true), 1e-9, 1 - 1e-9), y)))
        assert r["crps_oracle_scaled"] == pytest.approx(floor, rel=0.02)   # drops TO the shape floor
        assert crps - r["crps_oracle_scaled"] >= -1e-9                     # scale_error is non-negative
        if abs(c0) > 0.5:
            assert crps > r["crps_oracle_scaled"] * 1.05             # a real scale error is exposed


def test_s5_L_correct_scale_wrong_shape_leaves_the_error_in_capability():
    """Right level, wrong per-position shape => c* ~ 0 and the error stays in the capability term."""
    n_true = 4.0
    lam = np.repeat([2.0, 40.0], 10000)                              # two-level truth
    y = np.array([_nb_sample(m, n_true, 1, s)[0] for s, m in enumerate(lam)])
    mu = np.full_like(y, float(lam.mean()))                          # correct MEAN, no shape at all
    n = np.full_like(y, n_true)
    r = _oracle_scale(mu, n, y, seed=0)
    crps = float(np.mean(nb_crps(n, np.clip(n / (n + mu), 1e-9, 1 - 1e-9), y)))
    assert abs(r["c_star"]) < 0.75                                   # little scale left to fix
    assert (crps - r["crps_oracle_scaled"]) < 0.25 * r["crps_oracle_scaled"]   # error is capability


def test_s5_C_marginal_matches_a_bruteforce_grid_and_is_never_a_point_mass():
    rng = np.random.default_rng(0)
    for zero_frac in (0.4, 0.7, 0.95):                                # 4/8 real assays have median 0
        y = np.where(rng.random(8000) < zero_frac, 0.0,
                     _nb_sample(20.0, 3.0, 8000, 1) + 1.0)
        m = _marginal_nb(y)
        if zero_frac >= 0.7:
            assert m["marg_mu_legacy_median"] < 1e-3                 # legacy: a point mass at 0...
            assert m["marg_crps_legacy_median"] == pytest.approx(float(y.mean()), rel=0.02)  # ...= mean(y)
        assert m["marg_mu"] > 0.0                                    # honest: never a point mass
        assert m["marg_crps"] <= m["marg_crps_legacy_median"] + 1e-9  # ...and never worse
        # brute force over an independent, finer grid evaluated on the raw samples (no histogram)
        best = min(
            (float(np.mean(nb_crps(np.full_like(y, nn), np.clip(nn / (nn + mm), 1e-9, 1 - 1e-9), y))),
             mm, nn)
            for mm in np.geomspace(max(y.mean(), 1e-3) / 6, max(y.mean(), 1e-3) * 6, 25)
            for nn in np.geomspace(0.05, 50.0, 15))
        assert m["marg_crps"] <= best[0] * 1.02


def test_s5_C_decomposition_is_additive_and_ordered():
    y = _nb_sample(10.0, 3.0, 5000, 2)
    n = np.full_like(y, 3.0)
    mu = np.full_like(y, 40.0)                                       # 4x too high
    r = _oracle_scale(mu, n, y, seed=0)
    crps = float(np.mean(nb_crps(n, np.clip(n / (n + mu), 1e-9, 1 - 1e-9), y)))
    scale_error = crps - r["crps_oracle_scaled"]
    assert r["crps_oracle_scaled"] + scale_error == pytest.approx(crps, abs=1e-12)   # additive
    assert scale_error > 0                                           # a 4x level error is fixable...
    assert r["crps_oracle_scaled_and_n"] <= r["crps_oracle_scaled"] + 1e-9   # ...n-oracle only helps
    assert _oracle_scale(mu, n, y, seed=0)["c_star"] == r["c_star"]  # deterministic


def test_s5_C_wired_into_eval_M1_per_assay():
    m = FakeM2Model("offset_only")
    units = [_m2_unit(m, true_depth=25.0, a=0, seed=0), _m2_unit(m, true_depth=24.0, a=1, seed=1)]
    r = eval_M1(m, units, CPU, budget=5000, seed=0)
    for pa in r["imp_per_assay"].values():
        for k in ("crps", "crps_oracle_scaled", "scale_error", "c_star", "marg_mu", "marg_crps"):
            assert k in pa and np.isfinite(pa[k])
        assert pa["marg_mu"] > 0.0
        assert pa["crps_oracle_scaled"] <= pa["crps"] + 1e-9
    for k in ("imp_macro_crps", "imp_macro_crps_oracle_scaled", "imp_macro_scale_error"):
        assert np.isfinite(r[k])
    assert r["imp_macro_scale_error"] == pytest.approx(
        r["imp_macro_crps"] - r["imp_macro_crps_oracle_scaled"], abs=1e-9)


# ---------------------------------------------------------------------------
# S6 (h48) — per-assay LABELS
#
# `sandbox.h5` writes assay columns in the CANDI handler's `experiment_aliases` order, not in
# `SANDBOX_ASSAYS` order, so every per-assay label in the q19 stack was permuted. Training is unaffected
# (integer assay_id only) => the numbers stand, only the biology reading changes. The order itself is
# verified against real data by `h48_real_checks.py --fix s6`; here we check the relabel is sound.
# ---------------------------------------------------------------------------

def test_s6_C_h5_assay_order_is_a_bijection_of_sandbox_assays():
    assert len(H5_ASSAY_ORDER) == len(SANDBOX_ASSAYS) == 8
    assert len(set(H5_ASSAY_ORDER)) == 8                      # nothing duplicated
    assert sorted(H5_ASSAY_ORDER) == sorted(SANDBOX_ASSAYS)   # nothing dropped or invented
    assert H5_ASSAY_ORDER != list(SANDBOX_ASSAYS)             # ...and it really is a different order
    # the two headline relabels the audit calls out
    assert H5_ASSAY_ORDER[0] == "DNase-seq" and SANDBOX_ASSAYS[0] == "ATAC-seq"
    assert H5_ASSAY_ORDER[4] == "H3K9me3" and SANDBOX_ASSAYS[4] == "H3K27ac"


def test_s6_C_every_label_site_uses_the_new_order():
    src = Path(metrics_real.__file__).read_text()
    assert "SANDBOX_ASSAYS[a]" not in src                      # no label site left on the old order
    # >= the four original label sites (_per_assay, flip, depth sweep, ablation); the S14/S23
    # instruments add more, and any future one must use the corrected order too.
    assert src.count("H5_ASSAY_ORDER[a]") >= 4
    # the only surviving SANDBOX_ASSAYS uses must be non-labelling (a length, or the bijection assert)
    for line in src.splitlines():
        if "SANDBOX_ASSAYS" in line and not line.lstrip().startswith("#"):
            assert ("len(SANDBOX_ASSAYS)" in line or "import" in line
                    or "sorted(SANDBOX_ASSAYS)" in line), line


def test_s6_C_relabel_permutes_labels_without_touching_values():
    """The relabel must be a pure renaming: the same numbers, attached to different names."""
    m = FakeM2Model("offset_only")
    units = [_m2_unit(m, true_depth=25.0, a=0, seed=0), _m2_unit(m, true_depth=24.0, a=4, seed=1)]
    pa = eval_M1(m, units, CPU, budget=5000, seed=0)["imp_per_assay"]
    assert set(pa) == {H5_ASSAY_ORDER[0], H5_ASSAY_ORDER[4]} == {"DNase-seq", "H3K9me3"}
    assert set(pa) != {SANDBOX_ASSAYS[0], SANDBOX_ASSAYS[4]}
    assert all(np.isfinite(v["crps"]) for v in pa.values())
    sw = _depth_sweep(m, units, CPU, fg_frac=0.5, n_boot=50, seed=0)
    assert {t["target"][2] for t in sw["per_target"]} == {"DNase-seq", "H3K9me3"}


# ---------------------------------------------------------------------------
# S14/S23 (h48) — DSF counterfactual + z-controlled recoverability
# ---------------------------------------------------------------------------

class FakeS23Model(FakeM2Model):
    """Adds the two stubs the S23 sanity needs.

    `z_identity`: the decoder is BIT-EXACTLY blind to `y_meta` but its latent `z` already encodes the
    covariate. This is the case the probe exists to get right -- a probe that does not control for `z`
    reads it as "recoverable" even though the metadata pathway is dead.
    """

    def decoder(self, z, y_meta):
        if self.kind not in ("z_identity", "assay_responsive"):
            return super().decoder(z, y_meta)
        B, L, _ = z.shape
        A = y_meta.shape[2]
        if self.kind == "z_identity":
            eta = z[:, :1, 0].expand(B, L).unsqueeze(-1).expand(B, L, A) * 1.0   # from z ONLY
        else:
            aid = y_meta[:, 1, :]                                                # from y_meta ONLY
            eta = (0.7 * aid).unsqueeze(1).expand(B, L, A)
        mu = torch.pow(2.0, eta.clamp(-15, 30)).clamp_min(1e-6)
        n = torch.full_like(mu, self.n_const)
        return dict(mu=mu, n=n, p=(n / (n + mu)).clamp(1e-9, 1 - 1e-9), eta=eta, log2_mu=eta)


def _s23_units(model, n_per_assay=3, assays=(0, 1, 2, 3), B=2, L=48):
    """One unit per (assay, replicate); `z` is set to the assay id so `z_identity` can read it off."""
    units = []
    for a in assays:
        for r in range(n_per_assay):
            ym = torch.full((B, 4, 8), -1.0)
            ym[:, DEPTH_ROW, a] = 25.0
            ym[:, 1, a] = float(a)
            ym[:, READLEN_ROW, a] = 76.0
            ym[:, RUN_TYPE_ROW, a] = float(a % 2)
            z = torch.full((B, L, 2), float(a))
            imp = torch.zeros(B, L, 8, dtype=torch.bool)
            imp[:, :, a] = True
            gt = torch.zeros(B, L, 8)
            gt[:, :, a] = torch.arange(L, dtype=torch.float32).expand(B, L) + 1.0
            units.append(EvalUnit(z=z, y_meta_true=ym.clone(),
                                  den_map=torch.zeros(B, L, 8, dtype=torch.bool),
                                  y_data=torch.zeros(B, L, 8), imp_map=imp, y_data_imp=gt,
                                  y_meta_imp=ym.clone(), y_avail=torch.zeros(B, 8),
                                  biosample=f"T_b{a}", imp_biosample=f"V_b{a}_{r}"))
    return units


def test_s23_L_probe_separates_a_responsive_model_from_a_blind_one():
    vals = [0, 1, 2, 3]
    resp = _recoverability_probe(FakeS23Model("assay_responsive"), _s23_units(FakeS23Model("x")),
                                 1, vals, fg_frac=0.5)
    assert resp["chance"] == 0.25 and resp["accuracy"] > 0.9 and resp["recoverable"]

    blind = _recoverability_probe(FakeM2Model("depth_ignore"), _s23_units(FakeM2Model("x")),
                                  1, vals, fg_frac=0.5)
    assert blind["feature_energy"] == 0.0                    # nothing to learn from
    assert blind["accuracy"] == pytest.approx(0.25, abs=1e-9) and not blind["recoverable"]


def test_s23_L_z_control_is_load_bearing():
    """THE sanity check: a model whose `z` carries identity but whose `y_meta` path is DEAD.
    The non-z-controlled probe is fooled into "recoverable"; the z-controlled one must say chance."""
    m = FakeS23Model("z_identity")
    units = _s23_units(m)
    naive = _recoverability_probe(m, units, 1, [0, 1, 2, 3], z_controlled=False, fg_frac=0.5)
    assert naive["accuracy"] > 0.9 and naive["recoverable"]           # FOOLED by structural-z routing
    ctrl = _recoverability_probe(m, units, 1, [0, 1, 2, 3], z_controlled=True, fg_frac=0.5)
    assert ctrl["feature_energy"] == 0.0                             # z cancels within each target
    assert ctrl["accuracy"] == pytest.approx(0.25, abs=1e-9) and not ctrl["recoverable"]


def test_s23_C_probe_is_leave_target_out():
    """A target must never appear in its own training set: a probe that only memorises the target id
    (features == a per-target constant, identical across labels) must score exactly chance."""
    n_t, K = 6, 3
    X = np.repeat(np.arange(n_t, dtype=float), K)[:, None] * np.ones((1, 4))   # target id only
    y = np.tile(np.arange(K), n_t)
    g = np.repeat(np.arange(n_t), K)
    assert _leave_group_out_nearest_centroid(X, y, g) == pytest.approx(1.0 / K, abs=1e-9)
    # ...whereas a genuinely label-carrying feature is recovered
    X2 = np.tile(np.arange(K, dtype=float), n_t)[:, None] * np.ones((1, 4))
    assert _leave_group_out_nearest_centroid(X2, y, g) == pytest.approx(1.0, abs=1e-9)


def test_s14_L_dsf_counterfactual_needs_a_correctly_scaling_model():
    """CRPS(told=k, GT=k) < CRPS(told=1, GT=k): satisfied by a correct depth scaler, not by a blind one.
    Uses the same CRPS machinery as the instrument, on a hand-built 2-level counterfactual."""
    rng = np.random.default_rng(0)
    lam1 = rng.integers(5, 60, size=4000).astype(float)               # true dsf1 intensity
    n = np.full_like(lam1, 4.0)
    for k in (2, 4, 8):
        gt_k = np.floor(lam1 / k)                                     # counts_dsf{k} ~ 1/k downsample
        told_k = lam1 / k                                             # correct scaler
        told_1 = lam1                                                 # depth-blind: still predicts dsf1
        c_k = float(np.mean(nb_crps(n, np.clip(n / (n + told_k), 1e-9, 1 - 1e-9), gt_k)))
        c_1 = float(np.mean(nb_crps(n, np.clip(n / (n + told_1), 1e-9, 1 - 1e-9), gt_k)))
        assert c_k < c_1                                              # the bar discriminates...
        blind = float(np.mean(nb_crps(n, np.clip(n / (n + lam1), 1e-9, 1 - 1e-9), gt_k)))
        assert not (blind < c_1 - 1e-12)                              # ...and a blind model cannot pass


# ---------------------------------------------------------------------------
# M3 invariance controls
# ---------------------------------------------------------------------------

class FakeEncoder:
    """encode() -> a latent with a KNOWN invariance property; decoder unused for M3."""

    STRIDE = 32

    def __init__(self, kind, seed=0):
        self.kind = kind
        # projection of DNA sampled across the whole window (region-specific, DSF-invariant)
        n_pos = (19200 + self.STRIDE - 1) // self.STRIDE
        self.P = np.random.default_rng(seed).normal(size=(n_pos * 4, 8)).astype(np.float32)

    def eval(self):
        return self

    def _region_sig(self, x_dna, B):
        flat = x_dna[:, ::self.STRIDE, :].reshape(B, -1).float().cpu().numpy()
        return flat @ self.P                                 # [B, 8]

    def encode(self, x_data, x_dna, x_meta):
        B = x_data.shape[0]
        if self.kind == "invariant":                         # region sig from DNA only (DSF-invariant)
            z = torch.tensor(self._region_sig(x_dna, B), dtype=torch.float32) + 1.0   # bias -> nonzero norm
        elif self.kind == "non_invariant":                   # rotates with input depth (DSF-varying)
            d = x_meta[:, DEPTH_ROW, :].clamp_min(0).float().mean(dim=1)
            rot = torch.stack([torch.cos(3.0 * d), torch.sin(3.0 * d)], dim=1)         # [B, 2]
            z = rot + 0.01 * torch.tensor(self._region_sig(x_dna, B)[:, :2], dtype=torch.float32)
        elif self.kind == "collapsed":                       # constant latent
            z = torch.ones(B, 4)
        else:
            raise ValueError(self.kind)
        return z.unsqueeze(1)                                 # [B, 1, d]


def test_m3_invariant_encoder():
    fix = bake_fixture()
    r = eval_M3(FakeEncoder("invariant"), fix, CPU, n_regions=6, batch_size=2, seed=0)
    assert r["ratio"] < 0.1                                  # within (DSF) << between (region)
    assert r["invariance_ok"]


def test_m3_non_invariant_encoder():
    fix = bake_fixture()
    inv = eval_M3(FakeEncoder("invariant"), fix, CPU, n_regions=6, batch_size=2, seed=0)
    non = eval_M3(FakeEncoder("non_invariant"), fix, CPU, n_regions=6, batch_size=2, seed=0)
    assert non["ratio"] > inv["ratio"] + 0.2                # readout discriminates
    assert not non["invariance_ok"]


def test_m3_collapsed_encoder_trips_eff_rank_guard():
    fix = bake_fixture()
    r = eval_M3(FakeEncoder("collapsed"), fix, CPU, n_regions=6, batch_size=2, seed=0)
    # constant Z -> eff-rank guard trips regardless of the ratio value
    assert not r["invariance_ok"]
    assert (not np.isfinite(r["encoder_eff_rank"])) or r["encoder_eff_rank"] <= 1.0
